### ISSUE TITLE
Only top 1000 leaderboard entries analyzed

### ISSUE THREAD

**Issue by d-s-x** [dreignier/cgstats#16]
https://github.com/dreignier/cgstats/blob/fe61e72e197932bc7ebe79557d600b6f3dd5a8fa/cgstats.js#L130

they added 1000 users cap so this code no longer works as expected.

it is possible to call `getFilteredPuzzleLeaderboard` instead with body
`[game, user.publicHandle,,{active: true, column: "CODINGAMER", filter: "FOLLOWING"}]` but there is no easy way to get user's handle by user's name.

**Comment by dreignier** [comment]
Oh great, codingame broke cgstats for the non-top-1000 users ...
I know ony 2 way to get the user handle of a user:
 * Asking for it
 * Parse all the global leaderboard to find :(

**Comment by d-s-x** [comment]
> Oh great, codingame broke cgstats for the non-top-1000 users ...

not "1000 top users" but "1000 top **submissions**".

This includes mostly perl, ruby, bash etc submissions.
For example I have five 200-points entries for thor golf (c#, f#, scala, rust, vb) but only f#-one got into global top 1000, the rest are on 2000+ places because of bulky syntax. As a result the tool shows much smaller number instead of 1000 points.

> I know ony 2 way to get the user handle of a user:
> * Asking for it

looks good to me

> Parse all the global leaderboard to find

that's 8000+ pages, should be very slow


also I can suggest rather simple improvement to make it work for users with top-1000 submissions:

look for user's handle in first 1000 submissions and make another call to getFilteredPuzzleLeaderboard using that handle (well, this isn't 100% correct either because a user can follow large number of other users so total number of their submissions can be larger than 1000).

Is it possible to ask codingame staff to add paging for games leaderboards? Looks like this is the only way to guarantee that all user's submissions will be listed.

**Comment by dreignier** [comment]
I'll ask codingame if they can add an API to get a user id with a username.

**Comment by dreignier** [comment]
At the moment i'm on the community contest so i don't have much time for cgstats anyway :D

**Comment by d-s-x** [comment]
> I'll ask codingame if they can add an API to get a user id with a username.

Actually the API already exists.
I've checked through another tools and found it there: https://github.com/Orabig/CGPuzzleStats/blob/master/app/models/codingame_api.rb

`getGlobalLeaderboard` with body `[1, {"keyword": user}, "", true, "global"]`

It returns array of users whose pseudo contains `user` substring.

>  i don't have much time for cgstats anyway

what about pull requests then? ;)

**Comment by dreignier** [comment]
Any pull requrests are welcome !
